build=standard
displayName=Clogman Mode
author=mozjay
description=Restricts item usage based on collection log unlocks (and more!)
tags=collection,log,clog,bronzeman,restriction,ironman
plugins=com.clogman.ClogmanPlugin
version=1.3.0